I think im done with the sound system.

diff --git a/scripts/audioctl b/scripts/audioctl
--- a/scripts/audioctl
+++ b/scripts/audioctl
@@ -18,11 +18,104 @@ show_help()
     echo "Note: --setup requires sudo privileges"
 }
 
+# Will say if the current sound output is muted or not
+get_status()
+{
+    status=`amixer get Master | grep "Left.*%" | cut -d" " -f8 | sed "s/\[\(.*\)\]/\1/"`
+    if [ ! $? ]
+    then
+        >&2 echo "[ERROR]: amixer: could not retreive output mute status."
+        return 1
+    fi
+
+    if [ "$status" = "on" ]
+    then
+        echo " "
+    else
+        echo "(Muted)"
+    fi
+    return 0
+}
+
+# Volume percentage
+get_percentage()
+{
+    percentage=`amixer get Master | grep "Left.*%" | cut -d" " -f7 | sed "s/\[\(.*\)\%]/\1/"`
+    if [ ! $? ]
+    then
+        >&2 echo "[ERROR]: amixer: could not retreive the volume percentage."
+        return 1
+    fi
+    echo $percentage
+    return 0
+}
+
+# Notification icon depending of volume
+get_icon()
+{
+    percentage=`get_percentage`
+    if ((percentage == 0))
+    then
+        identify $hyprPath/ressources/volume-off.svg > /dev/null
+        if [ ! $? ]
+        then
+            >&2 echo "[ERROR]: icon: could not retreive the icon at $hyprPath/ressources/volume-off.svg."
+            return 1
+        fi
+        icon="$hyprPath/ressources/volume-off.svg"
+    fi
+
+    if ((percentage > 0 && percentage < 34))
+    then
+        identify $hyprPath/ressources/volume-low.svg > /dev/null
+        if [ ! $? ]
+        then
+            >&2 echo "[ERROR]: icon: could not retreive the icon at $hyprPath/ressources/volume-low.svg."
+            return 1
+        fi
+        icon="$hyprPath/ressources/volume-low.svg"
+    fi
+
+    if ((percentage > 33 && percentage < 67))
+    then
+        identify $hyprPath/ressources/volume-medium.svg > /dev/null
+        if [ ! $? ]
+        then
+            >&2 echo "[ERROR]: icon: could not retreive the icon at $hyprPath/ressources/volume-medium.svg."
+            return 1
+        fi
+        icon="$hyprPath/ressources/volume-medium.svg"
+    fi
+
+    if ((percentage > 66))
+    then
+        identify $hyprPath/ressources/volume-high.svg > /dev/null
+        if [ ! $? ]
+        then
+            >&2 echo "[ERROR]: icon: could not retreive the icon at $hyprPath/ressources/volume-high.svg."
+            return 1
+        fi
+        icon="$hyprPath/ressources/volume-high.svg"
+    fi
+
+    echo $icon
+    return 0
+}
+
+
+
 edit_volume()
 {
     local percentage="$1"
     local alsacfg="$2"
     local sign="$3"
+
+    # Is the percentage an integer ?
+    if [[ -n ${percentage//[0-9]/} ]]
+    then
+        >&2 echo "[ERROR]: $percentage: this is not an integer."
+        return 1 
+    fi
 
     # Is the percentage valid (between 0 and 100)
     if ((percentage < 0 || percentage > 100))
@@ -121,7 +214,8 @@ do
 	        exit 1
 	    fi
 
-            if [ ! `edit_volume $2 $3 +` ]
+	    edit_volume $2 $3 +
+	    if [ ! $? ]
 	    then
 	        >&2 echo "[ERROR]: $1 $2 $3: an error occured."
 	        show_help	
@@ -142,7 +236,8 @@ do
 	        exit 1
 	    fi
 
-            if [ ! `edit_volume $2 $3 -` ]
+	    edit_volume $2 $3 -
+            if [ ! $? ]
 	    then
 		>&2 echo "[ERROR]: $1 $2 $3: an error occured."
 		show_help
@@ -163,7 +258,8 @@ do
 	        exit 1
 	    fi
 
-            if [ ! `toggle_volume $2` ]
+	    toggle_volume $2
+            if [ ! $? ]
 	    then
 	        >&2 echo "[ERROR]: $1 $2: an error occured."
 		show_help
@@ -183,7 +279,8 @@ do
 	        exit 1
 	    fi
 
-            if [ ! `setup $2` ]
+	    setup $2
+            if [ ! $? ]
 	    then
 	        >&2 echo "[ERROR]: $1 $2: an error occured."
 		show_help
@@ -206,6 +303,43 @@ do
 
     esac
 done
+
+
+
+# === Notifying ===
+dunstctl -h > /dev/null
+if [ ! $? ]
+then
+    echo "Dunst is not installed. Install it if you wish to see sound notifications."
+else
+    # Mute status
+    muted=`get_status`
+    if [ ! $? ]
+    then
+        echo "[ERROR]: Could not retreive volume mute status."
+        show_help
+        exit 1
+    fi
+    # Percentage
+    percentage=`get_percentage`
+    if [ ! $? ]
+    then
+        echo "[ERROR]: Could not retreive volume percentage."
+        show_help
+        exit 1
+    fi
+    # Icon
+    icon=`get_icon`
+    if [ ! $? ]
+    then
+        echo "[ERROR]: Could not retreive notification icon."
+        show_help
+        exit 1
+    fi
+
+    # Notifying
+    $hyprPath/scripts/notifyctl -p $percentage -c 20 -t "System" -m "Volume : $percentage% $muted" -u 1 -e 3000 -i "$icon"
+fi
 
 # Done
 exit 0
diff --git a/scripts/notifyctl b/scripts/notifyctl
--- a/scripts/notifyctl
+++ b/scripts/notifyctl
@@ -15,6 +15,7 @@ show_help()
     echo "    -t, --title [string]         Title of the notification."
     echo "    -m, --message [string]       Text inside the notification."
     echo "    -u, --urgency [1|2|3]        Urgency of the notification. 1 is low, 2 is normal and 3 is urgent."
+    echo "    -e, --expiration [int]       Duration of the notification."
     echo "    -h, --help                   Show help."
 }
 
@@ -27,10 +28,11 @@ code=" "
 title="System"
 message=" "
 urgency=" "
+expiration=" "
 
 while [ $# -gt 0 ]
 do
-    case $1 in
+    case "$1" in
 
         -i|--icon)
             # Verifying passed arguments
@@ -44,7 +46,8 @@ do
             fi
 
             # Does the icon exist ?
-            if [ ! `identify $2` ]
+            identify "$2" > /dev/null
+            if [ ! "$?" ]
             then
                 echo
                 >&2 echo "[ERROR]: $2: the given file is not a valid icon."
@@ -164,10 +167,10 @@ do
             fi
 
             # Is the given value an int ?
-            if [[ -n ${input//[0-9]/} ]]
+            if [[ -n ${2//[0-9]/} ]]
             then
                 echo
-                >&2 echo "[ERROR]: $1: this is not an integer."
+                >&2 echo "[ERROR]: $2: this is not an integer."
                 echo "Usage: $0 $1 [1|2|3]"
                 show_help
                 exit 1 
@@ -201,6 +204,32 @@ do
             shift 2
         ;;
 
+        -e|--expiration)
+            # Verifying passed arguments
+            if [ $# -lt 2 ]
+            then
+                echo
+                >&2 echo "[ERROR]: $1: not enough arguments."
+                echo "Usage: $0 $1 [int]"
+                show_help
+                exit 1
+            fi
+
+            # Is the given value an int ?
+            if [[ -n ${input//[0-9]/} ]]
+            then
+                echo
+                >&2 echo "[ERROR]: $1: this is not an integer."
+                echo "Usage: $0 $1 [int]"
+                show_help
+                exit 1 
+            fi
+
+            # Else we are good to go
+            expiration="-t $2"
+            shift 2
+        ;;
+
         -h|--help)
             show_help
             shift 1
@@ -217,7 +246,7 @@ do
 done
 
 # Launching the notification
-dunstify $title $message $iconPath $code $progressBar $urgency
+dunstify "$title" "$message" $iconPath $code $progressBar $urgency $expiration
 
 # Done
 exit 0
